- clean: ['~']

- shell:
    - [mkdir -p ~/.ssh, Create ~/.ssh]

- link:
    ~/.dotfiles: ''
    ~/.bash: bash
    ~/.bashrc: bashrc
    ~/.dircolors: dircolors
    ~/.gitconfig: git/config
    ~/.gitignore_global: git/ignore
    ~/.ssh/config: ssh/config
    ~/.tmux.conf: tmux.conf
    ~/.Xresources: x/resources
    ~/.Xmodmap: x/modmap
    ~/.xsession: x/session
