" vim: set ft=vim:

call plug#begin('~/.vim/plugged')

Plug 'MarcWeber/vim-addon-mw-utils' | Plug 'tomtom/tlib_vim' | Plug 'garbas/vim-snipmate'
Plug 'Shougo/unite.vim'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'airblade/vim-gitgutter'
Plug 'altercation/vim-colors-solarized'
Plug 'bling/vim-airline'
Plug 'davidhalter/jedi-vim', {'for': 'python'}
Plug 'ervandew/supertab'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'

call plug#end()

"altercation/vim-colors-solarized
set background=dark
colorscheme solarized

"bling/vim-airline'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
set laststatus=2

"Shougo/unite.vim
let g:unite_source_grep_command = "ack-grep"
let g:unite_source_grep_default_opts = "-s -H --nopager --nocolor --nogroup --column --smart-case"
autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
    let b:SuperTabDisabled=1
    imap <buffer> <C-c> <Plug>(unite_exit)
    imap <buffer> <Tab> <Plug>(unite_select_next_line)
endfunction

"""
set nocompatible
set viminfo+=n~/.cache/viminfo
set updatetime=200

filetype plugin indent on

let mapleader = "\<Space>"

syntax on

set modeline
set modelines=2

set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

set cursorline
set number
set relativenumber
set showcmd

set wildmenu

set ignorecase
set smartcase

nnoremap # #zz
nnoremap * *zz
nnoremap / /\v
nnoremap ; :
nnoremap ;1 :!
nnoremap N Nzz
nnoremap n nzz

nnoremap <leader>[ :bprev<CR>
nnoremap <leader>] :bnext<CR>
nnoremap <leader>b :Unite -no-split -buffer-name=buffers -start-insert buffer<CR>
nnoremap <leader>d :bdelete<CR>
nnoremap <leader>f :Unite -no-split -buffer-name=files -start-insert file_rec/async:!<CR>
nnoremap <leader>/ :Unite -no-split -buffer-name=ack-grep -start-insert grep:.<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>yw byw
nnoremap <leader>w :w<CR>
vnoremap <leader>s :sort<CR>

silent! call repeat#set("\<Plug>GitGutterNextHunk", v:count)
silent! call repeat#set("\<Plug>GitGutterPrevHunk", v:count)
