#!/bin/sh

# Disable touchpad
xinput set-prop $(xinput list | perl -lnwe '/TouchPad.*?id=(\d+)/&&print $1') "Device Enabled" 0

# Per-window keyboard layout switching daemon
/usr/bin/kbdd

# Fix mouse buttons
/usr/bin/xmodmap $HOME/.Xmodmap

#eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11)
#export GNOME_KEYRING_CONTROL

# Bluetooth applet
/usr/bin/blueman-applet &

# Network manager applet
/usr/bin/nm-applet &

# Setup fonts vor vim-airline
if [[ -n $(which fc-cache) ]]; then
    fc-cache -f $HOME/.fonts
fi

# Setup display
xrandr -q | grep -q "HDMI1 connected"
if [ $? -eq 0 ]; then
    xrandr --output HDMI1 --primary --mode 1920x1080 --left-of LVDS1
fi

# Go awesome! :)
exec /usr/bin/awesome
