# vim: set ft=sh:

# If not running interactively, don't do anything
[[ ! $- == *i* ]] && return


shopt -s autocd
shopt -s cdspell
shopt -s checkwinsize
shopt -s histappend
shopt -u hostcomplete
shopt -s no_empty_cmd_completion


HISTCONTROL=ignoreboth:erasedups
HISTFILE="${HOME}/.cache/bash_history"
HISTFILESIZE=5000
HISTIGNORE=mc:bc:cd:ls:ll:la:vim:rtorrent
HISTSIZE=1000


bind -f "${HOME}/.config/inputrc"
bind '"\C-f": menu-complete'

export PYENV_ROOT="${HOME}/.pyenv"
export PATH="${PYENV_ROOT}/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
source ~/.pyenv/completions/pyenv.bash


export ACKRC="${HOME}/.config/ackrc"
export BC_ENV_ARGS="${HOME}/.config/bc/init"
export EDITOR="/usr/bin/vim"
export LESSHISTFILE="${HOME}/.cache/less_history"
export PATH="${HOME}/.local/bin:${PATH}"

if [[ $(hostname --domain) == bank24.int ]]; then
    export PIP_TRUSTED_HOST=pypi.python.org
fi

[[ -x /usr/bin/dircolors ]] && eval $(dircolors -b)  # Set LS_COLORS


alias ...='cd ../..'
alias ..='cd ..'
alias ack="$(which ack-grep 2>/dev/null || which ack 2>/dev/null) --color"
alias bc='bc -q'
alias df='df -h'
alias du='du -h'
alias egrep='egrep --color=auto'
alias gi='git'
alias grep='grep --color=auto'
alias igrep='grep --color=auto -i'
alias ipython3='ptipython3'
alias ipython='ptipython3'
alias la='ls -la --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias ltail='clear; tail -fn0'
alias pie='perl -pi -e'
alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'
alias tree='tree --dirsfirst -C'


for x in ${HOME}/.config/bash/*; do
    if [[ -d $x ]]; then
        for f in ${x}/*.sh; do
            [[ -r $f ]] && . $f
        done
    fi
done
